---
--- Generated by Luanalysis
--- Created by Mico.
--- DateTime: 2022/8/3 16:48
---

--local lock = KEYS[1]
--local ip   = ARGV[1]
--local ttl  = ARGV[2] + 0

local ip = redis.call('GET', KEYS[1])
-- 目前没有运行的实例
if ip == false then
    local result = redis.call('SET', KEYS[1],  ARGV[1], 'NX', 'EX', ARGV[2]) -- 抢锁
    if result ~= false and result.ok == 'OK' then
        return 1 -- 抢锁成功
    end

-- 目前已经有运行的实例
else if ip ~= false and ip == ARGV[1] then
    redis.call('EXPIRE', KEYS[1], ARGV[2]) -- 抢到锁的机器，续期
    return 2 -- 续期成功
end
end

return 0 -- 抢锁失败
